# Generated by Django 5.0.4 on 2024-04-29 18:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(default='')),
                ('eliminada', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tarea',
            },
        ),
        migrations.CreateModel(
            name='SubTarea',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField(default='')),
                ('eliminada', models.BooleanField(default=False)),
                ('tarea_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafioadl.tarea')),
            ],
            options={
                'db_table': 'subtarea',
            },
        ),
    ]
